/**
 * Florida Civil Procedure - Data Configuration
 * Complete workflow specification with timing, costs, documents, and decision logic
 */

export const STAGE_COLORS = {
    Filing: "#3b82f6",
    Service: "#0891b2",
    ServiceIssue: "#0e7490",
    Responsive: "#8b5cf6",
    Resolution: "#10b981",
    CaseMgmt: "#14b8a6",
    ADR: "#22c55e",
    Discovery: "#f59e0b",
    DiscTools: "#fb923c",
    DiscMotions: "#ea580c",
    ExpertDisc: "#f97316",
    Settlement: "#84cc16",
    PreTrial: "#ef4444",
    Trial: "#ec4899",
    PostTrial: "#6366f1",
    Enforce: "#8b5cf6",
    Appeal: "#14b8a6"
};

export const NODES = [
    {
        id: 0,
        name: "Complaint\nFiled",
        rule: "1.100",
        x: 100,
        y: 700,
        stage: "Filing",
        volume: 100,
        duration: "Day 1",
        cost: "2-5h+$400",
        documents: ["Complaint", "Summons"],
        owner: "Attorney",
        trigger: "File",
        deadline: "flexible"
    },
    {
        id: 1,
        name: "Service\nRequired",
        rule: "1.070",
        x: 260,
        y: 200,
        stage: "Service",
        volume: 100,
        duration: "120d",
        cost: "$50-200",
        documents: ["Summons"],
        owner: "Paralegal",
        trigger: "Auto",
        deadline: "strict",
        isDecision: true
    },
    {
        id: 2,
        name: "Personal\nService",
        rule: "1.070(b)",
        x: 420,
        y: 150,
        stage: "Service",
        volume: 60,
        duration: "1-30d",
        cost: "$75-150",
        documents: ["Return of Service"],
        owner: "Process Server",
        trigger: "Known Address",
        deadline: "strict"
    },
    {
        id: 3,
        name: "Substituted\nService",
        rule: "1.070(e)",
        x: 420,
        y: 230,
        stage: "Service",
        volume: 25,
        duration: "15-45d",
        cost: "$100-200",
        documents: ["Affidavit of Service"],
        owner: "Process Server",
        trigger: "Unknown Location",
        deadline: "strict"
    },
    {
        id: 4,
        name: "Publication",
        rule: "1.070(d)",
        x: 420,
        y: 310,
        stage: "Service",
        volume: 3,
        duration: "60-90d",
        cost: "$200-500",
        documents: ["Motion for Service by Publication"],
        owner: "Attorney",
        trigger: "Court Order Required",
        deadline: "strict"
    },
    {
        id: 5,
        name: "Service\nComplete",
        rule: "1.070(i)",
        x: 580,
        y: 240,
        stage: "Service",
        volume: 92,
        duration: "10d",
        cost: "1h",
        documents: ["Proof of Service"],
        owner: "Paralegal",
        trigger: "Valid Service",
        deadline: "strict"
    },
    {
        id: 6,
        name: "Insufficient\nService",
        rule: "1.140(b)",
        x: 580,
        y: 380,
        stage: "ServiceIssue",
        volume: 8,
        duration: "n/a",
        cost: "2-4h",
        documents: ["Motion to Quash"],
        owner: "Opposing Counsel",
        trigger: "Improper Service",
        deadline: "flexible",
        isException: true
    },
    {
        id: 7,
        name: "MTD Filed",
        rule: "1.140",
        x: 740,
        y: 500,
        stage: "Responsive",
        volume: 35,
        duration: "20d",
        cost: "15-30h",
        documents: ["Motion to Dismiss", "Memorandum of Law"],
        owner: "Opposing Counsel",
        trigger: "Legal Defect",
        deadline: "strict",
        isDecision: true
    },
    {
        id: 8,
        name: "Answer\nFiled",
        rule: "1.110",
        x: 740,
        y: 750,
        stage: "Responsive",
        volume: 65,
        duration: "20d",
        cost: "10-20h",
        documents: ["Answer"],
        owner: "Opposing Counsel",
        trigger: "No MTD Filed",
        deadline: "strict"
    },
    {
        id: 9,
        name: "MTD\nGranted",
        rule: "1.140",
        x: 900,
        y: 450,
        stage: "Resolution",
        volume: 12,
        duration: "30-60d",
        cost: "n/a",
        documents: ["Court Order"],
        owner: "Court",
        trigger: "Defective Complaint",
        deadline: "flexible"
    },
    {
        id: 10,
        name: "MTD\nDenied",
        rule: "",
        x: 900,
        y: 550,
        stage: "Responsive",
        volume: 23,
        duration: "30-60d",
        cost: "n/a",
        documents: ["Court Order"],
        owner: "Court",
        trigger: "Valid Complaint",
        deadline: "flexible"
    },
    {
        id: 11,
        name: "Case Mgmt\nConference",
        rule: "1.200",
        x: 1060,
        y: 700,
        stage: "CaseMgmt",
        volume: 88,
        duration: "45-90d",
        cost: "3-5h",
        documents: ["Case Management Order"],
        owner: "Court",
        trigger: "Answer Filed",
        deadline: "court-set"
    },
    {
        id: 12,
        name: "Mediation",
        rule: "1.700",
        x: 1220,
        y: 600,
        stage: "ADR",
        volume: 70,
        duration: "90-180d",
        cost: "8-16h+$1.5K",
        documents: ["Mediation Statement"],
        owner: "All Parties",
        trigger: "Court Ordered",
        deadline: "court-set",
        isDecision: true
    },
    {
        id: 13,
        name: "Settlement",
        rule: "1.730",
        x: 1380,
        y: 550,
        stage: "Resolution",
        volume: 28,
        duration: "30d",
        cost: "5-10h",
        documents: ["Settlement Agreement"],
        owner: "Attorneys",
        trigger: "Agreement Reached",
        deadline: "flexible"
    },
    {
        id: 14,
        name: "Discovery\nBegins",
        rule: "1.280",
        x: 1380,
        y: 800,
        stage: "Discovery",
        volume: 60,
        duration: "6-12mo",
        cost: "80-200h",
        documents: ["Discovery Plan"],
        owner: "Attorney",
        trigger: "Scheduling Order",
        deadline: "court-set"
    },
    {
        id: 15,
        name: "Interrogatories",
        rule: "1.340",
        x: 1540,
        y: 750,
        stage: "DiscTools",
        volume: 60,
        duration: "30d response",
        cost: "10-20h",
        documents: ["Interrogatories"],
        owner: "Attorney",
        trigger: "Discovery Request Served",
        deadline: "strict"
    },
    {
        id: 16,
        name: "RFPs",
        rule: "1.350",
        x: 1540,
        y: 830,
        stage: "DiscTools",
        volume: 60,
        duration: "30d response",
        cost: "15-40h",
        documents: ["Request for Production"],
        owner: "Paralegal",
        trigger: "Discovery Request Served",
        deadline: "strict"
    },
    {
        id: 17,
        name: "Discovery\nDispute?",
        rule: "",
        x: 1700,
        y: 790,
        stage: "DiscMotions",
        volume: 35,
        duration: "n/a",
        cost: "n/a",
        documents: [],
        owner: "n/a",
        trigger: "After 30d Response Period",
        deadline: "flexible",
        isDecision: true
    },
    {
        id: 18,
        name: "Motion to\nCompel",
        rule: "1.380",
        x: 1860,
        y: 760,
        stage: "DiscMotions",
        volume: 25,
        duration: "30d",
        cost: "8-15h",
        documents: ["Motion to Compel"],
        owner: "Attorney",
        trigger: "Failed to Respond",
        deadline: "flexible"
    },
    {
        id: 19,
        name: "Expert\nDesignation",
        rule: "1.280(b)(5)",
        x: 1700,
        y: 900,
        stage: "ExpertDisc",
        volume: 50,
        duration: "90d before trial",
        cost: "5-10h+$5K+",
        documents: ["Expert Report"],
        owner: "Expert Witness",
        trigger: "Expert Needed",
        deadline: "court-set"
    },
    {
        id: 20,
        name: "Summary\nJudgment",
        rule: "1.510",
        x: 2020,
        y: 800,
        stage: "PreTrial",
        volume: 32,
        duration: "Post-Discovery",
        cost: "40-80h",
        documents: ["MSJ", "Statement of Facts"],
        owner: "Attorney",
        trigger: "No Material Facts",
        deadline: "court-set",
        isDecision: true
    },
    {
        id: 21,
        name: "MSJ\nGranted",
        rule: "",
        x: 2180,
        y: 750,
        stage: "Resolution",
        volume: 16,
        duration: "30-60d",
        cost: "n/a",
        documents: ["Final Judgment"],
        owner: "Court",
        trigger: "No Genuine Issues",
        deadline: "flexible"
    },
    {
        id: 22,
        name: "MSJ\nDenied",
        rule: "",
        x: 2180,
        y: 850,
        stage: "PreTrial",
        volume: 16,
        duration: "30-60d",
        cost: "n/a",
        documents: ["Court Order"],
        owner: "Court",
        trigger: "Material Issues Exist",
        deadline: "flexible"
    },
    {
        id: 23,
        name: "Offer of\nJudgment",
        rule: "768.79",
        x: 2340,
        y: 700,
        stage: "Settlement",
        volume: 20,
        duration: "45d before trial",
        cost: "3-5h",
        documents: ["Proposal for Settlement"],
        owner: "Attorney",
        trigger: "Strategic Timing",
        deadline: "strict",
        isDecision: true
    },
    {
        id: 24,
        name: "Pretrial\nConference",
        rule: "1.200",
        x: 2500,
        y: 800,
        stage: "PreTrial",
        volume: 15,
        duration: "30d before trial",
        cost: "10-20h",
        documents: ["Pretrial Statement"],
        owner: "Attorney",
        trigger: "Trial Approaching",
        deadline: "court-set",
        isDecision: true
    },
    {
        id: 25,
        name: "Final\nSettlement",
        rule: "",
        x: 2660,
        y: 700,
        stage: "Resolution",
        volume: 9,
        duration: "Immediate",
        cost: "5-10h",
        documents: ["Settlement Agreement"],
        owner: "All Parties",
        trigger: "Agreement Reached",
        deadline: "flexible"
    },
    {
        id: 26,
        name: "Trial",
        rule: "1.430",
        x: 2660,
        y: 850,
        stage: "Trial",
        volume: 6,
        duration: "3-15 days",
        cost: "200-400h",
        documents: ["Trial Exhibits"],
        owner: "Attorney",
        trigger: "No Settlement",
        deadline: "court-set"
    },
    {
        id: 27,
        name: "Verdict",
        rule: "1.480",
        x: 2820,
        y: 850,
        stage: "Trial",
        volume: 6,
        duration: "Same Day",
        cost: "n/a",
        documents: ["Jury Verdict"],
        owner: "Jury/Judge",
        trigger: "End of Trial",
        deadline: "court-set"
    },
    {
        id: 28,
        name: "Post-Trial\nMotions?",
        rule: "1.530",
        x: 2980,
        y: 850,
        stage: "PostTrial",
        volume: 2.5,
        duration: "15d",
        cost: "20-40h",
        documents: ["Motion"],
        owner: "Attorney",
        trigger: "Legal Error?",
        deadline: "strict",
        isDecision: true
    },
    {
        id: 29,
        name: "New Trial\nMotion",
        rule: "1.530",
        x: 3140,
        y: 800,
        stage: "PostTrial",
        volume: 1.5,
        duration: "30d",
        cost: "25-50h",
        documents: ["Motion for New Trial"],
        owner: "Attorney",
        trigger: "Error Identified",
        deadline: "strict"
    },
    {
        id: 30,
        name: "Final\nJudgment",
        rule: "1.080(a)",
        x: 3300,
        y: 850,
        stage: "PostTrial",
        volume: 6,
        duration: "10d",
        cost: "3-5h",
        documents: ["Final Judgment"],
        owner: "Court",
        trigger: "Case Finalized",
        deadline: "strict"
    },
    {
        id: 31,
        name: "Enforcement?",
        rule: "1.550",
        x: 3460,
        y: 750,
        stage: "Enforce",
        volume: 4,
        duration: "n/a",
        cost: "n/a",
        documents: [],
        owner: "Client",
        trigger: "Non-Payment",
        deadline: "flexible",
        isDecision: true
    },
    {
        id: 32,
        name: "Execution",
        rule: "Ch. 77",
        x: 3620,
        y: 720,
        stage: "Enforce",
        volume: 3,
        duration: "Ongoing",
        cost: "10-30h",
        documents: ["Writ of Execution"],
        owner: "Sheriff",
        trigger: "Assets Identified",
        deadline: "flexible"
    },
    {
        id: 33,
        name: "Appeal?",
        rule: "9.110",
        x: 3460,
        y: 950,
        stage: "Appeal",
        volume: 2,
        duration: "30d",
        cost: "n/a",
        documents: [],
        owner: "Client",
        trigger: "Reversible Error?",
        deadline: "strict",
        isDecision: true
    },
    {
        id: 34,
        name: "Notice of\nAppeal",
        rule: "9.110",
        x: 3620,
        y: 950,
        stage: "Appeal",
        volume: 2,
        duration: "30d",
        cost: "50-150h",
        documents: ["Notice of Appeal"],
        owner: "Attorney",
        trigger: "File Appeal",
        deadline: "strict"
    },
    // Exception paths
    {
        id: 100,
        name: "DEFAULT",
        rule: "1.500",
        x: 900,
        y: 800,
        stage: "Resolution",
        volume: 5,
        duration: "20d",
        cost: "5-10h",
        documents: ["Motion for Default"],
        owner: "Attorney",
        trigger: "No Answer Filed",
        deadline: "strict",
        isException: true
    },
    {
        id: 101,
        name: "DISMISSAL",
        rule: "1.420(b)",
        x: 1540,
        y: 950,
        stage: "Resolution",
        volume: 2,
        duration: "60d",
        cost: "n/a",
        documents: ["Order of Dismissal"],
        owner: "Court",
        trigger: "Lack of Prosecution",
        deadline: "court-set",
        isException: true
    },
    {
        id: 102,
        name: "SANCTIONS",
        rule: "1.380",
        x: 1860,
        y: 860,
        stage: "DiscMotions",
        volume: 3,
        duration: "After Order",
        cost: "Attorney Fees",
        documents: ["Sanctions Order"],
        owner: "Court",
        trigger: "Willful Violation",
        deadline: "flexible",
        isException: true
    }
];

export const LINKS = [
    { source: 0, target: 1, volume: 100, label: "Service Required", trigger: "Automatic" },
    { source: 1, target: 2, volume: 60, label: "Personal Service", trigger: "Known Address" },
    { source: 1, target: 3, volume: 25, label: "Substituted", trigger: "Unknown" },
    { source: 1, target: 4, volume: 3, label: "Publication", trigger: "Court Order" },
    { source: 2, target: 5, volume: 58, label: "Completed", trigger: "Valid" },
    { source: 3, target: 5, volume: 23, label: "Completed", trigger: "Valid" },
    { source: 4, target: 5, volume: 3, label: "Completed", trigger: "Valid" },
    { source: 2, target: 6, volume: 2, label: "Insufficient", trigger: "Bad Service", isException: true },
    { source: 5, target: 7, volume: 35, label: "MTD Filed", trigger: "Defect" },
    { source: 5, target: 8, volume: 57, label: "Answer", trigger: "20 Days" },
    { source: 7, target: 9, volume: 12, label: "Granted", trigger: "Defective" },
    { source: 7, target: 10, volume: 23, label: "Denied", trigger: "Valid" },
    { source: 5, target: 100, volume: 5, label: "Default", trigger: "No Answer", isException: true },
    { source: 8, target: 11, volume: 65, label: "Case Management", trigger: "Answer Filed" },
    { source: 10, target: 11, volume: 23, label: "Case Management", trigger: "Answer Required" },
    { source: 11, target: 12, volume: 70, label: "Mediation", trigger: "Court Order" },
    { source: 12, target: 13, volume: 28, label: "Settled", trigger: "Agreement" },
    { source: 12, target: 14, volume: 42, label: "Impasse", trigger: "No Deal" },
    { source: 11, target: 14, volume: 18, label: "Discovery", trigger: "No Mediation" },
    { source: 14, target: 15, volume: 60, label: "Interrogatories", trigger: "Discovery Plan" },
    { source: 14, target: 16, volume: 60, label: "RFPs", trigger: "Discovery Plan" },
    { source: 15, target: 17, volume: 35, label: "Check Compliance", trigger: "30 Days" },
    { source: 16, target: 17, volume: 35, label: "Check Compliance", trigger: "30 Days" },
    { source: 17, target: 18, volume: 25, label: "Motion to Compel", trigger: "Non-Compliance" },
    { source: 18, target: 102, volume: 3, label: "Sanctions", trigger: "Willful", isException: true },
    { source: 14, target: 101, volume: 2, label: "Dismissal", trigger: "Inactive", isException: true },
    { source: 14, target: 19, volume: 50, label: "Expert Designation", trigger: "90 Days Before" },
    { source: 14, target: 20, volume: 32, label: "Summary Judgment", trigger: "Discovery Complete" },
    { source: 20, target: 21, volume: 16, label: "Granted", trigger: "No Material Facts" },
    { source: 20, target: 22, volume: 16, label: "Denied", trigger: "Issues Remain" },
    { source: 22, target: 23, volume: 20, label: "Offer of Judgment", trigger: "Strategic" },
    { source: 22, target: 24, volume: 15, label: "Pretrial Conference", trigger: "Trial Soon" },
    { source: 24, target: 25, volume: 9, label: "Settled", trigger: "Agreement" },
    { source: 24, target: 26, volume: 6, label: "Trial", trigger: "No Settlement" },
    { source: 26, target: 27, volume: 6, label: "Verdict", trigger: "Trial End" },
    { source: 27, target: 28, volume: 2.5, label: "Consider Post-Trial", trigger: "15 Days" },
    { source: 28, target: 29, volume: 1.5, label: "File Motion", trigger: "Error Found" },
    { source: 27, target: 30, volume: 3.5, label: "Final Judgment", trigger: "Accept Verdict" },
    { source: 29, target: 30, volume: 1.5, label: "Final Judgment", trigger: "Motion Decided" },
    { source: 30, target: 31, volume: 4, label: "Enforce?", trigger: "Non-Payment" },
    { source: 31, target: 32, volume: 3, label: "Execute", trigger: "Assets Found" },
    { source: 30, target: 33, volume: 2, label: "Appeal?", trigger: "Error Alleged" },
    { source: 33, target: 34, volume: 2, label: "File Appeal", trigger: "Within 30 Days" }
];

export const CONFIG = {
    chart: {
        width: 3900,
        height: 1200,
        initialZoom: 0.42,
        minZoom: 0.2,
        maxZoom: 3
    },
    node: {
        width: 18,
        singleLineHeight: 28,
        multiLineHeight: 45,
        borderRadius: 3
    },
    decision: {
        size: 20
    },
    document: {
        width: 10,
        height: 14,
        offsetY: 4
    }
};
